const { logger } = require('@librechat/data-schemas');
const { SystemRoles } = require('librechat-data-provider');
const { Strategy: JwtStrategy, ExtractJwt } = require('passport-jwt');
const { getUserById, updateUser } = require('~/models');

/**
 * Proxy JWT Strategy
 * 
 * This strategy validates JWT tokens generated by the proxy.
 * Key differences from standard JWT strategy:
 * - Tokens are generated and managed by the proxy
 * - LibreChat validates but does NOT rotate these tokens
 * - Session management is handled by the proxy
 * 
 * Token provider cookie should be set to "proxy" for this strategy to be used.
 */
const cookies = require('cookie');

const fromAccessTokenCookie = (req) => {
  const cookieHeader = req.headers.cookie;
  if (!cookieHeader) {
    return null;
  }
  const parsed = cookies.parse(cookieHeader);
  return parsed.lc_access_token || null;
};

const proxyJwtLogin = () =>
  new JwtStrategy(
    {
      jwtFromRequest: ExtractJwt.fromExtractors([
        ExtractJwt.fromAuthHeaderAsBearerToken(),
        fromAccessTokenCookie,
      ]),
      secretOrKey: process.env.JWT_SECRET,
      passReqToCallback: false,
    },
    async (payload, done) => {
      try {
        // Validate that this is a proxy-generated token
        // Proxy tokens should have the standard structure: { id, username, provider, email, exp, iat }
        if (!payload?.id) {
          logger.warn('[proxyJwtLogin] Invalid token payload: missing user id');
          return done(null, false);
        }

        // Fetch user from database
        const user = await getUserById(payload.id, '-password -__v -totpSecret -backupCodes');
        
        if (!user) {
          logger.warn('[proxyJwtLogin] User not found for proxy token: ' + payload.id);
          return done(null, false);
        }

        // Ensure user has a role
        user.id = user._id.toString();
        if (!user.role) {
          user.role = SystemRoles.USER;
          await updateUser(user.id, { role: user.role });
        }

        // Log successful authentication
        logger.debug(`[proxyJwtLogin] Proxy token validated for user: ${user.email}`);

        // Return user object
        done(null, user);
      } catch (err) {
        logger.error('[proxyJwtLogin] Error validating proxy token:', err);
        done(err, false);
      }
    },
  );

module.exports = proxyJwtLogin;


